class DataPokja {
  final datas = [
    'Nama Lingkungan',
    'Jumlah PKBN',
    'Jumlah PKDRT',
    'Pola Asuh',
    'P PKBN Simulasi',
    'P PKBN Anggota',
    'P PKDRT Simulasi',
    'P PKDRT Anggota',
    'Pola Kelompok',
    'Pola Anggota',
    'Lansia Kelompok',
    'Lansia Anggota',
    'Gotong Royong Jumlah Kerja Bakti',
    'Gotong Royong Jumlah Rukung Kematian',
    'Gotong Royong Jumlah Keagamaan',
    'Gotong Royong Jumlah Jimpitan',
    'Gotong Royong Jumlah Arisan',
    'Keterangan',
    'Status',
  ];

  final Map<String, dynamic> newData = {
    "id": 141,
    "id_kec": 8,
    "id_kel": 65,
    "nama_ling": 'Kosong',
    "j_pkbn": 0,
    "j_pkdrt": 0,
    "pola_asuh": 0,
    "p_pkbn_simulasi": 0,
    "p_pkbn_anggota": 0,
    "p_pkdrt_simulasi": 0,
    "p_pkdrt_anggota": 0,
    "pola_kelompok": 0,
    "pola_anggota": 0,
    "lansia_kelompok": 0,
    "lansia_anggota": 0,
    "g_jum_ker": 0,
    "g_jum_ruk": 0,
    "g_jum_agama": 0,
    "g_jum_jimpit": 0,
    "g_jum_arisan": 0,
    "ket": 'Kosong',
    "status": 1,
  };
}
