class DataPokjab {
  final datas = [
    'Nama Lingkungan',
    'JUMLAH WARGA YANG MASIH 3 BUTA	Laki',
    'JUMLAH WARGA YANG MASIH 3 BUTA	Perempuan',
    'Jumlah Paket A Kel. Belajar',
    'Jumlah Paket A Warga Belajar',
    'Jumlah Paket B Kel. Belajar',
    'Jumlah Paket B Warga Belajar',
    'Jumlah Paket C Kel. Belajar',
    'Jumlah Paket C Warga Belajar',
    'Jumlah KF Belajar',
    'Jumlah Kj Warga Belajar',
    'Jumlah Paud Sejenis',
    'Jumlah Taman Baca Perpus',
    'Jumlah BKB Kelompok',
    'Jumlah BKB Ibu Peserta',
    'Jumlah BKB Ape(SET)',
    'Jumlah BKB Kel Simulasi',
    'Jumlah Kader Tutor KF',
    'Jumlah Kader Tutor Paud',
    'Jumlah kader BKB',
    'Jumlah Kader Koperasi',
    'Jumlah Kader Keterampilan',
    'Jumlah Kader Latih LP3PKK',
    'Jumlah Kader Latih TP3PKK',
    'Jumlah Kader Latih Damas PKK',
    'Pengembangan Koperasi Pemula Kelompok',
    'Pengembangan Koperasi Pemula Peserta',
    'Pengembangan Koperasi Madya Kelompok',
    'Pengembangan Koperasi Madya Peserta',
    'Pengembangan Koperasi Utama Kelompok',
    'Pengembangan Koperasi Utama Peserta',
    'Pengembangan Koperasi Mandiri Kelompok',
    'Pengembangan Koperasi Mandiri Peserta',
    'Koperasi Badan Hukum Jumlah Kelompok',
    'Koperasi Badan Hukum Jumlah Peserta',
    'Keterangan',
    'Status'
  ];
}
