class DataModel {
  final datas = [
    "Nama Lingkungan",
    "Jumlah Keluarga",
    "Jumlah Lingkungan",
    "Jumlah RW",
    "Jumlah RT",
    "Jumlah Dasa wisma",
    "Jumlah Kepala Rumah Tangga",
    "Jumlah KK",
    "Jumlah Anggota Keluarga Total Laki-laki",
    "Jumlah Anggota Keluarga Total Perempuan",
    "Jumlah Balita Keluarga Total Laki-laki",
    "Jumlah Balita Keluarga Total Perempuan",
    "Jumlah Anggota Keluarga PUS",
    "Jumlah Anggota Keluarga WUS",
    "Jumlah Anggota Keluarga Ibu Hamil",
    "Jumlah Anggota Keluarga Ibu menyusui",
    "Jumlah Anggota Keluarga Lansia",
    "Jumlah Anggota Keluarga 3 Buta Laki-laki",
    "Jumlah Anggota Keluarga 3 Buta Perempuan",
    "Jumlah Anggota Keluarga Berkebutuhan khusus",
    "Kriteria Rumah Sehat",
    "Kriteria Rumah Tidak Sehat",
    "Jumlah Rumah memiliki Tj_rw Pembuangan Sampah",
    "Jumlah Rumah memiliki SPAL",
    "Jumlah Rumah memiliki Jamban Keluarga",
    "Jumlah Rumah memiliki Stiker P4K",
    "Sumber Air Keluarga Pdam",
    "Sumber Air Keluarga Sumur",
    "Sumber Air Keluarga Sungai",
    "Sumber Air Keluarga DLL",
    "Makanan Pokok Beras",
    "Makanan Pokok Non Beras",
    "Jumlah KK Yang memiliki tabung",
    "Keluarga Mengikuti Kegiatan UP2K",
    "Keluarga Mengikuti Kegiatan Pemanfaatan Peternakan",
    "Keluarga Mengikuti Kegiatan Pemanfaatan Perikanan",
    "Keluarga Mengikuti Kegiatan Pemanfaatan Warung Hidup",
    "Keluarga Mengikuti Kegiatan Pemanfaatan Lumbung Hidup",
    "Keluarga Mengikuti Kegiatan Pemanfaatan Toga",
    "Keluarga Mengikuti Kegiatan Tanaman Keras",
    "Keluarga Mengikuti Kegiatan Industri Pangan",
    "Keluarga Mengikuti Kegiatan Industri Sandang",
    "Keluarga Mengikuti Kegiatan Industri Jasa",
    "Keluarga Mengikuti Kegiatan Kesehatan Lingkungan",
    "Keterangan",
    "Status"
  ];

  final Map<String, dynamic> newData = {
    "id": 141,
    "id_kec": 8,
    "id_kel": 65,
    "nama_ling": null,
    "j_kel": 0,
    "j_ling": 0,
    "j_rw": 0,
    "j_rt": 0,
    "j_dasawisma": 0,
    "j_krt": 0,
    "j_kk": 0,
    "j_a_total_l": 0,
    "j_a_total_p": 0,
    "j_a_balita_l": 0,
    "j_a_balita_p": 0,
    "j_a_pus": 0,
    "j_a_wus": 0,
    "j_a_hamil": 0,
    "j_a_susui": 0,
    "j_a_lansia": 0,
    "j_a_blaki": 0,
    "j_a_bcwe": 0,
    "j_a_bb": 0,
    "kr_sehat": 0,
    "kr_tdk_sehat": 0,
    "jr_tsampah": 0,
    "jr_spal": 0,
    "jr_jamban": 0,
    "jr_stiker": 0,
    "sak_pdam": 0,
    "sak_sumur": 0,
    "sak_sungai": 0,
    "sak_dll": 0,
    "mp_beras": 0,
    "mp_nonberas": 0,
    "jkk_tabung": 0,
    "k_upk": 0,
    "kp_ternak": 0,
    "kp_ikan": 0,
    "kp_warung": 0,
    "kp_lumbung": 0,
    "kp_toga": 0,
    "kp_tanaman": 0,
    "i_pangan": 0,
    "i_sandang": 0,
    "i_jasa": 0,
    "kes_ling": 0,
    "ket": null,
    "status": 1
  };
}
